vscode:
extensions:
- csstools.postcss
- octref.vetur
- tabnine.tabnine-vscode
- csstools.postcss
- esbenp.prettier-vscode
- dbaeumer.vscode-eslint
- antfu.vite
- antfu.iconify
- antfu.theme-vitesse
- xabikos.javascriptsnippets
- editorconfig.editorconfig
- antfu.theme-vitesse
