image: gitpod/workspace-mongodb

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: |
      mongod
  - prebuild: |
      npm install -global pnpm
      pnpm install
      pnpm build
      pnpm dev
    command: |
      npm run start

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - csstools.postcss
    - octref.vetur
    - tabnine.tabnine-vscode
    - csstools.postcss
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - antfu.vite
    - antfu.iconify
    - antfu.theme-vitesse
    - xabikos.javascriptsnippets
    - editorconfig.editorconfig
    - antfu.theme-vitesse
